Userstep
tcunis/bisosprob pull request #20
Opened 2022-07-04 08:55 UTC by renatoloureiro

I believe the new step is working fine and well written, the only aspect that I would like to discuss is if it's a good idea that the user defined function receives the variable `prob` every time. Also this new step can only have one output, i.e. one variable as output.

2022-08-10 17:50 UTC, tcunis requested changes
We should not provide the problem structure to the user-defined function. I don't think it's good style and may also lead to confusion if the user is not aware of such a first parameter to their function. In order to provide variables beyond the decision variables, I suggest a mechanism similar to `outputfcn`, where the user provides a cell array of arguments when registering the step.

2022-08-10 17:50 UTC, tcunis commented on +bisos/+iteration/+step/transfer.m
> +            'Number of inputs is incorrect %d\nShould be %d', length(input), nargin(fun_handle)-1);
Please keep the message for the exception on a single line. Also, be a little more specific: Number of which inputs do you mean?

2022-08-10 17:50 UTC, tcunis commented on +bisos/+iteration/+step/transfer.m
> +        assert(length(output)==1, 'Not a single output');
Be more specific, 
```suggestion
        assert(length(output)==1, 'Function handle must return exactly one output.');
```

2022-08-10 17:50 UTC, tcunis commented on +bisos/+iteration/+step/transfer.m
> +        sol.(step.varout{1}) = step.fun(prob, a{:});
Do not forward problem structure to function handle.

2022-08-12 19:18 UTC, renatoloureiro commented
With the latest commit https://github.com/tcunis/bisosprob/pull/20/commits/50a138ed1119e6c2b2d9d5c9c794dfd09986994d , all the previous requested changes have been  handled

2022-08-15 08:42 UTC, tcunis approved these changes
Looks good to me. I have just tidied up the demos. Why do we allow the `transfer` step to only change a single variable?

2022-08-15 08:43 UTC, merged

2022-08-15 08:53 UTC, renatoloureiro commented
> Looks good to me. I have just tidied up the demos. Why do we allow the `transfer` step to only change a single variable?

Right now with the current step, it only allows for a single output, i.e. change in only one variable. I understand that we could extend this to multiple outputs instead of just one, but I decided that it would be better to just have one output. So that while using it, the output depends on all inputs, simple example:
 p, V <- b, c, a    (multiple outputs)
equivalent to
p <- b
V <-c, a

all outputs don't necessarily depend on all inputs in the multiple outputs case.